In [1]:
import numpy as np

In [2]:
x = np.matrix([[1, 1], [1, 3], [1, 4], [1, 5]])

In [3]:
x

matrix([[1, 1],
        [1, 3],
        [1, 4],
        [1, 5]])

In [4]:
y = np.matrix([[3], [2], [5], [4]])

In [5]:
y

matrix([[3],
        [2],
        [5],
        [4]])

In [7]:
[beta, residuals, rank, s] = np.linalg.lstsq(x, y, rcond=-1)

In [8]:
beta

matrix([[2.2],
        [0.4]])

In [9]:
test_data = np.matrix([[1, 2], [1, 2.5], [1, 1.75]])

In [10]:
test_data

matrix([[1.  , 2.  ],
        [1.  , 2.5 ],
        [1.  , 1.75]])

In [11]:
predictions = np.matmul(test_data, beta)

In [12]:
predictions

matrix([[3. ],
        [3.2],
        [2.9]])